import { z } from "zod";

/**
 * §18 — the font library. Every family here is SIL Open Font Licence via
 * Google Fonts, so it can ship in commercial exports. Premium/licensed
 * families get added with `source: "licensed"` and a licence reference.
 */
export const FontRole = z.enum(["headline", "support", "accent"]);
export type FontRole = z.infer<typeof FontRole>;

export const FontFamilyMeta = z.object({
  family: z.string(),
  googleFamily: z.string().optional(),
  source: z.enum(["google", "local", "licensed"]).default("google"),
  licence: z.string().default("OFL-1.1"),
  category: z.enum(["sans", "serif", "display", "mono", "script"]),
  width: z.enum(["condensed", "normal", "wide"]).default("normal"),
  /** §18 "personality" — feeds the planner's font choice. */
  personality: z.array(z.string()).default([]),
  roles: z.array(FontRole).min(1),
  weights: z.array(z.number().int()).min(1),
  italics: z.boolean().default(false),
  pairsWith: z.array(z.string()).default([]),
  languages: z.array(z.string()).default(["latin"]),
  /** Optical correction: caps-heavy display faces need tighter default tracking. */
  defaultTracking: z.number().default(0),
});
export type FontFamilyMeta = z.infer<typeof FontFamilyMeta>;

export const FONT_CATALOGUE: FontFamilyMeta[] = [
  {
    family: "Archivo Black",
    source: "google",
    licence: "OFL-1.1",
    category: "display",
    width: "normal",
    personality: ["bold", "confident", "modern", "editorial"],
    roles: ["headline"],
    weights: [400],
    italics: false,
    pairsWith: ["Inter", "Archivo", "DM Sans"],
    languages: ["latin"],
    defaultTracking: -0.02,
  },
  {
    family: "Anton",
    source: "google",
    licence: "OFL-1.1",
    category: "display",
    width: "condensed",
    personality: ["loud", "poster", "impactful", "energetic"],
    roles: ["headline"],
    weights: [400],
    italics: false,
    pairsWith: ["Inter", "Work Sans", "Barlow"],
    languages: ["latin"],
    defaultTracking: -0.01,
  },
  {
    family: "Bebas Neue",
    source: "google",
    licence: "OFL-1.1",
    category: "display",
    width: "condensed",
    personality: ["condensed", "bold", "energetic", "headline", "modern"],
    roles: ["headline", "accent"],
    weights: [400],
    italics: false,
    pairsWith: ["Inter", "Manrope", "Space Grotesk"],
    languages: ["latin"],
    defaultTracking: 0.02,
  },
  {
    family: "Oswald",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "condensed",
    personality: ["condensed", "utilitarian", "strong", "newsy"],
    roles: ["headline", "accent"],
    weights: [300, 400, 500, 600, 700],
    italics: false,
    pairsWith: ["Inter", "Lora", "Work Sans"],
    languages: ["latin", "cyrillic"],
    defaultTracking: 0,
  },
  {
    family: "Barlow Condensed",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "condensed",
    personality: ["clean", "athletic", "efficient", "modern"],
    roles: ["headline", "support", "accent"],
    weights: [300, 400, 500, 600, 700, 800],
    italics: true,
    pairsWith: ["Barlow", "Inter"],
    languages: ["latin"],
    defaultTracking: 0.01,
  },
  {
    family: "Big Shoulders Display",
    source: "google",
    licence: "OFL-1.1",
    category: "display",
    width: "condensed",
    personality: ["urban", "tall", "dramatic", "contemporary"],
    roles: ["headline"],
    weights: [400, 600, 700, 800, 900],
    italics: false,
    pairsWith: ["Inter", "DM Sans"],
    languages: ["latin"],
    defaultTracking: 0.01,
  },
  {
    family: "Syne",
    source: "google",
    licence: "OFL-1.1",
    category: "display",
    width: "normal",
    personality: ["futuristic", "quirky", "arts", "distinctive"],
    roles: ["headline", "accent"],
    weights: [400, 500, 600, 700, 800],
    italics: false,
    pairsWith: ["Inter", "Space Grotesk"],
    languages: ["latin"],
    defaultTracking: -0.01,
  },
  {
    family: "Unbounded",
    source: "google",
    licence: "OFL-1.1",
    category: "display",
    width: "wide",
    personality: ["futuristic", "geometric", "confident", "tech"],
    roles: ["headline"],
    weights: [300, 400, 600, 700, 800, 900],
    italics: false,
    pairsWith: ["Inter", "Manrope"],
    languages: ["latin", "cyrillic"],
    defaultTracking: -0.02,
  },
  {
    family: "Playfair Display",
    source: "google",
    licence: "OFL-1.1",
    category: "serif",
    width: "normal",
    personality: ["elegant", "luxury", "editorial", "classic"],
    roles: ["headline", "accent"],
    weights: [400, 500, 600, 700, 800, 900],
    italics: true,
    pairsWith: ["Inter", "Manrope", "Work Sans"],
    languages: ["latin", "cyrillic"],
    defaultTracking: -0.01,
  },
  {
    family: "Cormorant Garamond",
    source: "google",
    licence: "OFL-1.1",
    category: "serif",
    width: "normal",
    personality: ["refined", "delicate", "wedding", "luxury"],
    roles: ["headline", "accent"],
    weights: [300, 400, 500, 600, 700],
    italics: true,
    pairsWith: ["Inter", "Jost", "Work Sans"],
    languages: ["latin"],
    defaultTracking: 0.01,
  },
  {
    family: "Instrument Serif",
    source: "google",
    licence: "OFL-1.1",
    category: "serif",
    width: "normal",
    personality: ["editorial", "contemporary", "high-contrast", "premium"],
    roles: ["headline", "accent"],
    weights: [400],
    italics: true,
    pairsWith: ["Inter", "DM Sans", "Sora"],
    languages: ["latin"],
    defaultTracking: -0.01,
  },
  {
    family: "Bricolage Grotesque",
    source: "google",
    licence: "OFL-1.1",
    category: "display",
    width: "normal",
    personality: ["expressive", "modern", "friendly", "editorial"],
    roles: ["headline", "support"],
    weights: [200, 300, 400, 500, 600, 700, 800],
    italics: false,
    pairsWith: ["Inter", "DM Sans"],
    languages: ["latin"],
    defaultTracking: -0.01,
  },
  {
    family: "Inter",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["neutral", "clear", "modern", "ui"],
    roles: ["support", "headline"],
    weights: [300, 400, 500, 600, 700, 800, 900],
    italics: true,
    pairsWith: ["Archivo Black", "Anton", "Playfair Display"],
    languages: ["latin", "cyrillic", "greek"],
    defaultTracking: 0,
  },
  {
    family: "Manrope",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["geometric", "friendly", "modern", "clean"],
    roles: ["support", "headline"],
    weights: [300, 400, 500, 600, 700, 800],
    italics: false,
    pairsWith: ["Bebas Neue", "Playfair Display"],
    languages: ["latin"],
    defaultTracking: 0,
  },
  {
    family: "DM Sans",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["warm", "geometric", "approachable", "clean"],
    roles: ["support"],
    weights: [300, 400, 500, 600, 700, 800, 900],
    italics: true,
    pairsWith: ["Archivo Black", "Instrument Serif"],
    languages: ["latin"],
    defaultTracking: 0,
  },
  {
    family: "Space Grotesk",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["technical", "quirky", "contemporary", "youthful"],
    roles: ["support", "accent"],
    weights: [300, 400, 500, 600, 700],
    italics: false,
    pairsWith: ["Syne", "Bebas Neue"],
    languages: ["latin"],
    defaultTracking: 0,
  },
  {
    family: "Sora",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["tech", "confident", "modern", "corporate"],
    roles: ["support", "headline"],
    weights: [300, 400, 500, 600, 700, 800],
    italics: false,
    pairsWith: ["Instrument Serif", "Inter"],
    languages: ["latin"],
    defaultTracking: 0,
  },
  {
    family: "Work Sans",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["neutral", "sturdy", "readable"],
    roles: ["support"],
    weights: [300, 400, 500, 600, 700, 800],
    italics: true,
    pairsWith: ["Anton", "Oswald", "Playfair Display"],
    languages: ["latin"],
    defaultTracking: 0,
  },
  {
    family: "Archivo",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["grotesque", "sturdy", "editorial"],
    roles: ["support", "headline"],
    weights: [300, 400, 500, 600, 700, 800, 900],
    italics: true,
    pairsWith: ["Archivo Black", "Instrument Serif"],
    languages: ["latin"],
    defaultTracking: 0,
  },
  {
    family: "Barlow",
    source: "google",
    licence: "OFL-1.1",
    category: "sans",
    width: "normal",
    personality: ["clean", "efficient", "athletic"],
    roles: ["support"],
    weights: [300, 400, 500, 600, 700, 800],
    italics: true,
    pairsWith: ["Barlow Condensed", "Anton"],
    languages: ["latin"],
    defaultTracking: 0,
  },
];

export const CATALOGUE_BY_FAMILY = new Map(FONT_CATALOGUE.map((f) => [f.family, f]));

export function familiesForRole(role: FontRole): FontFamilyMeta[] {
  return FONT_CATALOGUE.filter((f) => f.roles.includes(role));
}

/** Condensed one-line descriptions for the planner prompt — keeps tokens low (§32). */
export function catalogueDigest(): string {
  return FONT_CATALOGUE.map(
    (f) =>
      `${f.family} — ${f.category}/${f.width}; ${f.personality.join(", ")}; roles: ${f.roles.join("/")}; weights: ${f.weights.join(",")}`,
  ).join("\n");
}
